spring:
  profiles:
    active: dev


gleif-endpoints:
  uri: https://api.gleif.org/api/v1/lei-records
  pagination-uri: https://api.gleif.org/api/v1/lei-records?page[size]=pageSize&page[number]=pageNumber

gleif-appconfig:
  max-page-size: 200
  max-download-lei-records-per-session: 10000
